---
title: "Working Paper Citation Analysis"
author: "Wyatt Hurt"
date: "3/16/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(encoding="UTF-8")
library(dplyr)
library(janitor)
library(gt)
library(tidyr)
library(rorcid)
library(bibliometrix)
library(tidyverse)
```


```{r orcid_match}
orcid_df <- bib2df("raw_data/extracted_citations.bib") %>%
results <- biblioAnalysis(orcid_df)
# orcid(query = "alicia AND harley")
```

```{r}
# extracted_citations <- bib2df("raw_data/extracted_citations.bib") %>%
  clean_names() %>%
  select(doi) %>%
  filter(!is.na(doi)) %>%
  write_csv("extracted_citation_dois.csv")
```

```{r wos_r}

# Unable to use WOS API because not free :(

library(wosr)
auth(username = Sys.getenv("wyatthurt@college.harvard.edu"),
password = Sys.getenv("@Harvard2021"))

pull_wos(query, editions = c("SCI", "SSCI", "AHCI", "ISTP", "ISSHP",
"BSCI", "BHCI", "IC", "CCR", "ESCI"),
sid = auth(Sys.getenv("WOS_USERNAME"), Sys.getenv("WOS_PASSWORD")))
```

years %>%
  group_by(value) %>%
  summarize(year_ct = n()) %>%
  gt() %>%
  cols_label(value = "Year", year_ct = "Times Cited") %>%
  tab_header(title = "Articles Cited per Year") 
