---
title: "ARER SI"
author: "Wyatt Hurt"
date: "5/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
library(scales)
library(ggpubr)

# Define function that plots each search term over time.

graph_time <- function(name) {
  name %>%
  filter(publication_years < 2020) %>%
  filter(publication_years > 1979) %>%
  ggplot(aes(x = publication_years, y = records)) +
  geom_col(fill = "black") + 
  theme_transparent() + 
    labs(x = "Year",
         y = "Records") +
  theme(
        text = element_text(family="Times New Roman", color = "black")) + 
  theme(axis.line = element_line(color = "black"),
        axis.text = element_text(color = "black"),
        axis.title = element_text(color = "black"),
        axis.ticks = element_line(color = "black")) +
    expand_limits(x = c(1980,2019)) + 
  scale_x_continuous(breaks=c(1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019),
                     label = c("'80", "'85", "'90", "'95", "'00", "'05", "'10", "'15", "'19"))
}
```


```{r}

# Create all graphs using the above-defined graph function.

cas <- read_csv("cas.csv") %>%
  clean_names
graph_time(cas) +
  ylim(0,19)
ggsave("cas.png", scale = .6, bg = "transparent")

chans <- read_csv("chans.csv") %>%
  clean_names
graph_time(chans) +
  ylim(0,60)
ggsave("chans.png", scale = .6, bg = "transparent")

ches <- read_csv("ches.csv") %>%
  clean_names
graph_time(ches) +
  ylim(0,15)
ggsave("ches.png", scale = .6, bg = "transparent")

esg <- read_csv("esg.csv") %>%
  clean_names
graph_time(esg) +
  ylim(0,13)
ggsave("esg.png", scale = .6, bg = "transparent")

# Deprecated 
ecosystem_services <- read_csv("ecosystem_services.csv") %>%
  clean_names
graph_time(ecosystem_services) +
  ylim(0,19)
ggsave("ecosystem_services.png", scale = .6, bg = "transparent")

ecosystem_services_2 <- read_csv("ecosystem_services_2.csv") %>%
  clean_names
graph_time(ecosystem_services_2) +
  ylim(0,1336)
ggsave("ecosystem_services_2.png", scale = .6, bg = "transparent")

environmental_justice <- read_csv("environmental_justice.csv") %>%
  clean_names
graph_time(environmental_justice) +
  ylim(0,546)
ggsave("environmental_justice.png", scale = .6, bg = "transparent")

industrial_ecology <- read_csv("industrial_ecology.csv") %>%
  clean_names
graph_time(industrial_ecology) +
  ylim(0,802)
ggsave("industrial_ecology.png", scale = .6, bg = "transparent")

ipbes <- read_csv("ipbes.csv") %>%
  clean_names
graph_time(ipbes) +
  ylim(0,32)
ggsave("ipbes.png", scale = .6, bg = "transparent")

livelihoods <- read_csv("livelihoods.csv") %>%
  clean_names
graph_time(livelihoods) +
  ylim(0,1752)
ggsave("livelihoods.png", scale = .6, bg = "transparent")

pathways <- read_csv("pathways.csv") %>%
  clean_names
graph_time(pathways) +
  ylim(0,93)
ggsave("pathways.png", scale = .6, bg = "transparent")

resilience <- read_csv("resilience.csv") %>%
  clean_names
graph_time(resilience) +
  ylim(0,661)
ggsave("resilience.png", scale = .6, bg = "transparent")

ses1 <- read_csv("ses1.csv") %>%
  clean_names
graph_time(ses1) +
  ylim(0,17)
ggsave("ses1.png", scale = .6, bg = "transparent")

ses2 <- read_csv("ses2.csv") %>%
  clean_names
graph_time(ses2) +
  ylim(0,201)
ggsave("ses2.png", scale = .6, bg = "transparent")

mlp <- read_csv("mlp.csv") %>%
  clean_names
graph_time(mlp) +
  ylim(0,326)
ggsave("mlp.png", scale = .6, bg = "transparent")

scp <- read_csv("scp.csv") %>%
  clean_names
graph_time(scp) +
  ylim(0,32)
ggsave("scp.png", scale = .6, bg = "transparent")

welfare <- read_csv("welfare.csv") %>%
  clean_names
graph_time(welfare) +
  ylim(0,31)
ggsave("welfare.png", scale = .6, bg = "transparent")

# Deprecated 
welfare_2 <- read_csv("welfare_2.csv") %>%
  clean_names
graph_time(welfare_2) +
  ylim(0,19)
ggsave("welfare_2.png", scale = .6, bg = "transparent")
```

```{r}

# Create table of top organizations, by the frequency with which they appear in
# the top 5 of each framework search.

top_organizations <- read_csv("top_organizations.csv")

top_organizations_freq <- top_organizations %>%
  group_by(organization_name) %>%
  summarize(frequency = sum(dummy)) %>%
  arrange(desc(frequency))

write_csv(top_organizations_freq, "top_organizations_freq.csv")

# Create table of top organizations, by their proportion out of the total
# articles for all frameworks.

top_organizations_count <- top_organizations %>%
  group_by(organization_name) %>%
  summarize(frequency = sum(count)) %>%
  arrange(desc(frequency)) %>%
  mutate(frequency = paste(round(100*frequency/33089, 2), "%", sep = ""))

write_csv(top_organizations_count, "top_organizations_count.csv")
```

```{r}

# Create table of top journals, by the frequency with which they appear in
# the top 5 of each framework search.

top_journals <- read_csv("top_journals.csv")

top_journals_freq <- top_journals %>%
  group_by(journal_name) %>%
  summarize(frequency = sum(dummy)) %>%
  arrange(desc(frequency))

write_csv(top_journals_freq, "top_journals_freq.csv")

# Create table of top journals, by their proportion out of the total
# articles for all frameworks.

top_journals_count <- top_journals %>%
  group_by(journal_name) %>%
  summarize(frequency = sum(count)) %>%
  arrange(desc(frequency)) %>%
  mutate(frequency = paste(round(100*frequency/33089, 2), "%", sep = ""))

write_csv(top_journals_count, "top_journals_count.csv")
```


```{r include = FALSE}

# Create a table showing the relative frequency of each framework. Now
# deprecated.

framework_table %>%
  ggplot(aes(x = reorder(name_s_alphabetical, desc(number_of_pubs_2000_2019)), y = number_of_pubs_2000_2019)) + 
  scale_y_log10() +
    scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) +
  geom_col(fill = "gray25") + 
  theme_classic() +
  labs(title = "Number of Citations", 
       subtitle = "2000 - 2019, Web of Science (All indexes; articles, book, book chapters)",
       x = "Framework",
       y = "Citation Count") +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        text = element_text(family="Times New Roman"))
```
